# Configuration for Account object permissions
record_types:
  - Customer
  - Partner
  - Supplier

fields:
  read:
    - Name
    - Description
    - Industry
    - Type
    - Website
    - Phone
    - BillingAddress
    - ShippingAddress
    - AccountNumber
    - Site
    - AccountSource
    - AnnualRevenue
    - NumberOfEmployees
    - Ownership
    - TickerSymbol
    - Rating
    - ParentId
    - CreatedDate
    - LastModifiedDate

  edit:
    - Name
    - Description
    - Industry
    - Type
    - Website
    - Phone
    - BillingStreet
    - BillingCity
    - BillingState
    - BillingPostalCode
    - BillingCountry
    - ShippingStreet
    - ShippingCity
    - ShippingState
    - ShippingPostalCode
    - ShippingCountry
    - AccountSource
    - AnnualRevenue
    - NumberOfEmployees
    - Rating

restricted_fields:
  - OwnerId
  - SystemModstamp
  - LastActivityDate
  - Jigsaw
  - JigsawCompanyId
  - CleanStatus
